# Tools production configuration
services:
  tools-prod:
    image: ${DOCKER_USERNAME:-suho}/suho-tools:${TOOLS_IMAGE_TAG:-latest}
    container_name: tools-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tools.rule=Host(`tools.${DOMAIN}`)"
      - "traefik.http.routers.tools.entrypoints=websecure"
      - "traefik.http.routers.tools.tls=true"
      - "traefik.http.routers.tools.tls.certresolver=letsencrypt"
      - "traefik.http.services.tools.loadbalancer.server.port=3000"
    profiles:
      - prod