# Main server compose file with modular includes
# Using merge behavior: https://docs.docker.com/reference/compose-file/merge/

include:
  # Common resources
  - path: ./common/networks.yml
  - path: ./common/volumes.yml
  
  # Traefik service configurations
  - path: ./traefik/dev.yml
  - path: ./traefik/prod.yml
  
  # Tools service configurations
  - path: ./tools/dev.yml
  - path: ./tools/prod.yml
  
  # Root service configurations
  - path: ./root/dev.yml
  - path: ./root/prod.yml

  # Gunthy service configurations
  - path: ./gunthy/dev.yml
  - path: ./gunthy/prod.yml
