# Gunthy development configuration
services:
  gunthy-dev:
    image: ${DOCKER_USERNAME:-riemannulus}/gunthy:${GUNTHY_IMAGE_TAG:-latest}
    container_name: gunthy-dev
    restart: unless-stopped
    environment:
      - USE_PM2=false
    networks:
      - web
    volumes:
      - ./gunthy_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gunthy.rule=Host(`gunthy.localhost`)"
      - "traefik.http.routers.gunthy.entrypoints=web"
      - "traefik.http.services.gunthy.loadbalancer.server.port=3001"
    profiles:
      - dev
